-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 07:50:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finanza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finanza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finanza` DEFAULT CHARACTER SET utf8 ;
USE `finanza` ;

-- -----------------------------------------------------
-- Table `finanza`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idempresa` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `rol` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_empresa_usuario`
    FOREIGN KEY (`idempresa`)
    REFERENCES `finanza`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_empresa_usuario_idx` ON `finanza`.`usuario` (`idempresa` ASC) ;


-- -----------------------------------------------------
-- Table `finanza`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`acceso` (
  `idacceso` INT NOT NULL AUTO_INCREMENT,
  `iduasuario` INT NOT NULL,
  PRIMARY KEY (`idacceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`registroWalet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`registroWalet` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `numerowallet` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idregistro`),
  CONSTRAINT `fk_usuario:_recarga`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario:_recarga_idx` ON `finanza`.`registroWalet` (`idusuario` ASC) ;


-- -----------------------------------------------------
-- Table `finanza`.` recarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.` recarga` (
  `id recarga` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  ` fecha` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id recarga`),
  CONSTRAINT `fk_recarga_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recarga_usuario_idx` ON `finanza`.` recarga` (`idusuario` ASC) ;


-- -----------------------------------------------------
-- Table `finanza`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`transaccion` (
  `idtransaccion` INT NOT NULL AUTO_INCREMENT,
  `idusario` INT NOT NULL,
  `detalle` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidadRetirar` FLOAT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idtransaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`tareas` (
  `idtareas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idtareas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`detalleTarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`detalleTarea` (
  `iddetalleTarea` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idtarea` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`iddetalleTarea`),
  CONSTRAINT `fk_detalleTarea_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleTarea_tarea`
    FOREIGN KEY (`idtarea`)
    REFERENCES `finanza`.`tareas` (`idtareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalleTarea_usuario_idx` ON `finanza`.`detalleTarea` (`idusuario` ASC) ;

CREATE INDEX `fk_detalleTarea_tarea_idx` ON `finanza`.`detalleTarea` (`idtarea` ASC) ;


-- -----------------------------------------------------
-- Table `finanza`.`ganancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finanza`.`ganancia` (
  `idsaldo` INT NOT NULL,
  `iddetalleTarea` INT NOT NULL,
  `saldo` FLOAT NOT NULL,
  PRIMARY KEY (`idsaldo`),
  CONSTRAINT `fk_ganacia_detalleTarea`
    FOREIGN KEY (`iddetalleTarea`)
    REFERENCES `finanza`.`detalleTarea` (`iddetalleTarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ganacia_detalleTarea_idx` ON `finanza`.`ganancia` (`iddetalleTarea` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
