-- MySQL Script generated by MySQL Workbench
-- Thu May 26 11:01:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finanza
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `finanza` ;

-- -----------------------------------------------------
-- Schema finanza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finanza` DEFAULT CHARACTER SET utf8 ;
USE `finanza` ;

-- -----------------------------------------------------
-- Table `finanza`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`usuario` ;

CREATE TABLE IF NOT EXISTS `finanza`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idempresa` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(100) NULL,
  `condicion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`roles` ;

CREATE TABLE IF NOT EXISTS `finanza`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`permiso` ;

CREATE TABLE IF NOT EXISTS `finanza`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`usuario_permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`usuario_permiso` ;

CREATE TABLE IF NOT EXISTS `finanza`.`usuario_permiso` (
  `idusuario_permiso` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idusuario_permiso`),
  CONSTRAINT `fk_usuaripermiso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariopermiso_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `finanza`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuaripermiso_usuario_idx` ON `finanza`.`usuario_permiso` (`idusuario` ASC);

CREATE INDEX `fk_usuariopermiso_permiso_idx` ON `finanza`.`usuario_permiso` (`idpermiso` ASC);


-- -----------------------------------------------------
-- Table `finanza`.`registroWalet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`registroWalet` ;

CREATE TABLE IF NOT EXISTS `finanza`.`registroWalet` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `numerowallet` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idregistro`),
  CONSTRAINT `fk_usuario:_recarga`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario:_recarga_idx` ON `finanza`.`registroWalet` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `finanza`.` recarga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.` recarga` ;

CREATE TABLE IF NOT EXISTS `finanza`.` recarga` (
  `id recarga` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  ` fecha` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id recarga`),
  CONSTRAINT `fk_recarga_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recarga_usuario_idx` ON `finanza`.` recarga` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `finanza`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `finanza`.`transaccion` (
  `idtransaccion` INT NOT NULL AUTO_INCREMENT,
  `idusario` INT NOT NULL,
  `detalle` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidadRetirar` FLOAT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idtransaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`tareas` ;

CREATE TABLE IF NOT EXISTS `finanza`.`tareas` (
  `idtareas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idtareas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanza`.`detalleTarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`detalleTarea` ;

CREATE TABLE IF NOT EXISTS `finanza`.`detalleTarea` (
  `iddetalleTarea` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idtarea` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`iddetalleTarea`),
  CONSTRAINT `fk_detalleTarea_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `finanza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleTarea_tarea`
    FOREIGN KEY (`idtarea`)
    REFERENCES `finanza`.`tareas` (`idtareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalleTarea_usuario_idx` ON `finanza`.`detalleTarea` (`idusuario` ASC);

CREATE INDEX `fk_detalleTarea_tarea_idx` ON `finanza`.`detalleTarea` (`idtarea` ASC);


-- -----------------------------------------------------
-- Table `finanza`.`ganancia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanza`.`ganancia` ;

CREATE TABLE IF NOT EXISTS `finanza`.`ganancia` (
  `idsaldo` INT NOT NULL,
  `iddetalleTarea` INT NOT NULL,
  `saldo` FLOAT NOT NULL,
  PRIMARY KEY (`idsaldo`),
  CONSTRAINT `fk_ganacia_detalleTarea`
    FOREIGN KEY (`iddetalleTarea`)
    REFERENCES `finanza`.`detalleTarea` (`iddetalleTarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ganacia_detalleTarea_idx` ON `finanza`.`ganancia` (`iddetalleTarea` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
